### PR TITLE
Determine daily detector offsets

### PR DESCRIPTION
**Pull request by 153957**
Implementation for #90

Todo:
- Graphs
    - On config page?
- Migrations
    - [x] Create migration for new field
    - [ ] Perform migration on server
- Test
    - [x] Jobs
    - [x] Source csv
- Determine detector offsets for existing data
    - [x] Script to perform this action 
    - [ ] Loop over all Summaries with event data and call `update_detector_timing_offsets`
- [x] Upgrade SAPPHiRE on server

### CODE REVIEW

**Comment by 153957** [comment]
This code should be useable to generate the offsets for existing summaries:

```python
from django_publicdb.histograms.models import Summary
from django_publicdb.histograms.jobs import update_detector_timing_offsets

from sapphire.utils import pbar

summaries = Summary.objects.filter(num_events__isnull=False, needs_update_events=False)

for summary in pbar(summaries.iterator(), length=summaries.count()):
    update_detector_timing_offsets(summary)
```

**Comment by 153957** [comment]
Upgraded SAPPHiRE on server
`envpub && pip install -U --no-deps hisparc-sapphire`

**Comment by 153957** [comment]
The determination of offsets for old data (before today) is running.. It claims to need 18hours to complete.. would probably be faster if we use multiprocessing.

**Comment by tomkooij** [comment]
Nice work!

**Comment by davidfokkema** [comment]
+1

**Comment by 153957** [comment]
Here is a small analysis on the first 570 [offsets for station 501](http://data.hisparc.nl/show/source/detector_timing_offsets/501/).
Note that the csv output from the publicdb automatically skips lines where the offsets have not changed. However, checking the difference between each subsequent timestamp 532 of the items are 1 day apart. The offset for a single detector can be the same while that for an other changes, causing the line to be included. Here is a histogram of the difference in offset between subsequent lines. 

change in offset 501

The maximum for each detector is at 0.0 ns and still high at 0.1 ns. The small changes of 0.1 ns can simply be caused by the accuracy of the fit. Perhaps instead of rounding the offsets to 1 decimal we should round them to a multiple of .25 ns, that would still provide good accuracy (relative to the sampling time of the electronics) and remove some of this jitter which may not be real changes but simply statistics.. This is not very important, because the data set is not extremely large (~3600 rows for 10 years), but could be significantly reduced, if the different rounding was used..

**Comment by 153957** [comment]
The processing of the 'old' data crashed on a bug in the code, that has been fixed. I also updated the code to use multiprocessing. At time of the crash the progressbar claimed it still needed ~17 hrs, the multiprocessing code (using 3 processes), claims to need ~6.5 hrs.

**Comment by 153957** [comment]
Finished processing all old data.

**Pull request merged**
