### PR TITLE
Import SerializedDataField from histograms.

### LINKED ISSUE #193: jSPARC analysis sessions broken: event data missing.
jSPARC analysis sessions are failing. (Both "get example" and actual requested sessions).

In the JSON that is returned by `http://data.hisparc.nl/jsparc/get_coincidence/?session_title=example&session_pin=1337&student_name=test` the event data seems to be missing:

```json
 "events":
 [{"status": "on",
 "timestamp": 1393725788,
 "altitude": 57.5165005522,
 "detectors": 0,
 "number": 502, 
"longitude": 4.95009211145,
 "integrals": [],
 "mips": [],
 "latitude": 52.3552939665,
 "pulseheights": [],
 "traces": [],
 "nanoseconds": 163936473},
```
The `traces`, `integrals`, `mips` are all empty lists, which results in reconstructed energy being 0 and everything failing.

Requested sessions have same result. I tried a day for which the stations have normal data.

### PR DESCRIPTION
**Pull request by tomkooij**
Fixes specific implementation of to_python() not being compatible with
postgress/BYTEA field.

Make it DRY.

This effectively reverts commit 311d7b8363721b7da563951ae84393c2e4ea5d48. Which implemented storing JSON fixtures in `SerializedDataFields`. As far as I can tell, this feature is unused.

As I cannot properly restore the database in my VM, I have not tested this fully. However, with this patch, I can read pulseheights, traces and integrals from Events (Coincidences) in the Django admin panel.

Fixes #193 
Fixes HiSPARC/jsparc#52

### CODE REVIEW

**Comment by tomkooij** [comment]
Travis is complaining about:

```
publicdb/histograms/esd.py:400:13: E722 do not use bare except'
publicdb/histograms/models.py:22:9: E722 do not use bare except'
publicdb/inforecords/models.py:506:5: E722 do not use bare except'
publicdb/inforecords/models.py:517:5: E722 do not use bare except'
publicdb/raw_data/forms.py:118:17: E722 do not use bare except'
```

Must be a new "feature" of a recent `flake8`. My `flake8` does not complain:
```
flake8 --version
3.2.1 (pyflakes: 1.3.0, pycodestyle: 2.2.0, mccabe: 0.5.3) CPython 2.7.12 on Windows
```

**Comment by 153957** [comment]
Indeed, new versions of flake8 have additional checks, I will ignore those for this PR and we can fix those in master. The easiest solution is to simply change those `except:` to `except Exception:`.

**Comment by tomkooij** [comment]
This does need some review:

I managed to restore the database dump, so I can view the existing jSPARC analysissession data:

The traces (`publicdb.coincidences.Events.traces`) are unpickled as: 
```[array([ 103.17,  101.46,  104.31 (... delete ...)  112.29])] ```

I'm not sure this is right. The existing code in `SerializedDataArray` had some logic for unpacking these numpy.arrays.

**Comment by 153957** [comment]
What does the JSON response look like when you retrieve such an event?

**Comment by tomkooij** [comment]
The response actually looks fine:

```json
"timestamp": 1393678285,
 "nanoseconds": 331031001, 
"events": [{"status": "on", "timestamp": 1393678285, "altitude": 57.5165005522, "detectors": 4, "number": 502, "longitude": 4.95009211145,
 "integrals": [0.0, 1814.02, 2661.9, 5057.32], 
"mips": [0.03705, 0.3933, 0.40755, 1.0031999999999999], 
"latitude": 52.3552939665, 
"pulseheights": [7.41, 78.66, 81.51, 200.64], 
"traces": [[-0.0,  ... ] 
```
The traces are huge but look fine: [full response](https://gist.github.com/tomkooij/bac6a1d464732f6b79de67114020565a)

**Comment by tomkooij** [comment]
Thanks!
Op vr 17 nov. 2017 om 23:34 schreef Arne de Laat <notifications@github.com>

**Pull request merged**
