### PR TITLE
Merge jsparc app views/urls into analysissessions.

### PR DESCRIPTION
**Pull request by 153957**
Deprecate old '/jsparc/…' urls.
The jsparc app/urls can be removed when jSparc repo has been updated to use `http://data.hisparc.nl/analysis-session/` as base url.

The jsparc app only contains some views and urls which are mostly based on models in the analysissessions and coincidences apps, moreover there are views in analysissessions closely related to those in jsparc. So it seems sensible to merge jsparc into analysissessions.

~~(Change target to master after #198 is merged)~~

### CODE REVIEW

**Comment by tomkooij** [comment]
Merging the `/jsparc` urls: +1
LGTM, but flake8 is complaining ;)

**Comment by davidfokkema** [comment]
I think this is a good idea. But maybe even simpler? Let's say ``/analysis``?

**Comment by 153957** [comment]
I'll fix the failing tests :)
Yes, we can also do that, that would also require updating the url/iframes to request sessions on hisparc.nl . Also check if those urls mentioned anywhere else; docs/infopakket/routenet.

**Comment by davidfokkema** [comment]
Ok, so changing the urls yet again will create some work. Maybe we should leave that up to Tom, Niek and Kasper.

**Comment by 153957** [comment]
Deploying this with the updated jSparc: https://github.com/HiSPARC/jsparc/commit/dbc8bf18227051b6c109ef9eb9c1108b4cf3e2d4

**Pull request merged**
