### PR TITLE
Add single rate plots to Network overview

### PR DESCRIPTION
**Pull request by tomkooij**
For @kaspervd 

Rename Coincidences to Network
Add singlerate (low threshold) plots to page

### CODE REVIEW

**Comment by 153957** [comment]
This will add ~60 plots to the page..? Or is to just for local usage?

**Comment by kaspervd** [comment]
Yes, this will make it easier to spot atmospheric disturbances traveling across our stations (see for example https://data.hisparc.nl/show/network/coincidences/2019/3/6/)

**Comment by 153957** [comment]
Ok, but why not perform this analysis locally? The relevance for general use does not seem very clear.

And why has this already been deployed even though this is still in a pull request?

**Comment by kaspervd** [comment]
Doing this locally is fine for me but @renaldo20 and @josst do not know how to work with hdf5 files. Also students can use this to easily look at weather fronts passing by. If there is disagreement on this we can think of different ways to display the information.

**Comment by 153957** [comment]
Ok. But they would still need to look for specific dates and then figure out the geographical location of each station, which is not obvious from that page.. and since you are looking for weather you could also include (barometer) data from our weather stations..
There are many other plots which can also be useful in some situations, but I suggest we try to keep it to a clear succinct set.

**Comment by renaldo20** [comment]
Not just for local use. In order to generate scientific interest for phenomena it has already proved a very usefull tool for teachers as well.
It is correct that further analysis is mandatory beyond these plots.
But the usefulness of a general overview of all singlerates that can be judged at a glance can hardly be overstated.
Addition of weatherstationdata will indeed be usefull.

My 5 cents
Reno

**Comment by 153957** [comment]
I still do not agree with just dumping all these plots on a single page. If you want to show a relation between weather and event/singles rates you can do that with a single station (if it has a weather station), this simply shows that it happens for multiple stations.

But on a related note:
There is no explanation for 'Singles' on the Help page: https://data.hisparc.nl/show/help/
This should be done anyway since these plots also appear on station data pages.

**Comment by davidfokkema** [comment]
I'm not opposed to including them. You can quickly spot an effect which affected multiple stations. After that you have to do more work because the geography is not clear. However, the plots do take up a lot of room and you have to scroll endlessly back and forth to look at multiple stations. May I humbly suggest something akin to sparklines? 😉

**Comment by tomkooij** [comment]
I put this together during my commute home last monday and immediately deployed it because it saves our collaborators a lot of time.

I do not have time to implement a better version of this any time soon.

**Pull request merged**
