### PR TITLE
Determination and storing of Time deltas

### PR DESCRIPTION
**Pull request by 153957**
Part of the work for #133

Daily determination and storing of time deltas.

Todos:
- [ ] ~~Possibly add coincidence id to TimeDelta tables~~
- [ ] Check if it works
    - [x] Tested for a single date to generate the deltas, including overwrite previous run

### CODE REVIEW

**Comment by 153957** [comment]
Tested it on a local ESD file, from 2014/1/16, it took less than 2 minutes (with detector offsets manually set to 0).

**Comment by tomkooij** [comment]
Nice. 2 minutes per day is still long enough to justify storing the delta's, but it does not add too much time to the daily processing of events. :+1:

**Comment by 153957** [comment]
Indeed, and the server can do it with multiple cores if it needs to be updated for multiple days simultaneously.. so should be fine.

**Comment by 153957** [comment]
Only thing to determine now is where in the jobs this task should be added, I think just after finding and storing coincidences. Then both the requirements (detector offsets and coincidences) should be available. The detector offsets are determined in the 'update_histograms' step, which is done before the update_coincidences (see [jobs.py#L186](https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/histograms/jobs.py#L186))

**Comment by tomkooij** [comment]
:+1: 

Shouldn't ```determine_time_differences()``` and ```store_time_deltas()``` be in SAPPHiRE? 
So we can test storing timedelta's and determining timing offsets "locally" using a cq?

**Comment by 153957** [comment]
Yes, that would probably be better. But where..? A new module in `sapphire.analysis`, perhaps `time_deltas` or `process_coincidences`? 😉

**Comment by tomkooij** [comment]
I prefer ```time_deltas```.

Or we could move most of the station timing offsets stuff out of ```calibration``` into a new module ```station_timing_offsets``` and add this as well ?

**Comment by 153957** [comment]
Hmm, I think it would be best to keep it separate, the determination of station and detector offsets should be kept together, since some of the steps are the same. Processing events and determining time deltas is preparation work that should be kept separate from the calibration, though clear links should be made (i.e. the requirement for processed events or time deltas for determining the offset).

**Pull request merged**
