### PR TITLE
Replace OpenLayers maps by Leaflet

### PR DESCRIPTION
**Pull request by 153957**
This replaces all OpenLayers maps by Leaflet.

Leaflet v1 is now released and is a more modern map provider than OpenLayers v2. There is an OpenLayers v3, but is not directly compatible with existing code, moreover, Leaflet is used for jSparc event display.

Todo:
- [x] Change marker size on zoom (old ratio: radius = 0.55 * zoomlevel)
- ~~Show all tooltips (labels) when zoomed in close~~ Not practical since tooltips show on mouseover, and not certain how to open multiple simultaneously.
- [x] Use retina tiles on retina displays
- [x] Increase contrast of tiles using CSS (as in event-display, simply update CSS selector)
- [x] Only show link to station data if it has data, or better yet, only show station marker if it has data.
- [x] Check performance
- ~~Perhaps move parts to templates for DRY~~ not that many chunks of duplicate code

Check if all works correctly on pages with maps:
- http://data.hisparc.nl/show/stations_on_map/
([vagrant](http://127.0.0.1:8081/show/stations_on_map/))
- http://data.hisparc.nl/show/stations_on_map/Netherlands/Nijmegen/
([vagrant](http://127.0.0.1:8081/show/stations_on_map/Netherlands/Nijmegen/))
- http://data.hisparc.nl/show/stations/501/
([vagrant](http://127.0.0.1:8081/show/stations/501/))
- http://data.hisparc.nl/show/stations/6/config/
([vagrant](http://127.0.0.1:8081/show/stations/6/config/))
- http://data.hisparc.nl/maps/
([vagrant](http://127.0.0.1:8081/maps/))
- http://data.hisparc.nl/maps/1008/
([vagrant](http://127.0.0.1:8081/maps/1008/))
- http://data.hisparc.nl/maps/United%20Kingdom/
([vagrant](http://127.0.0.1:8081/maps/United%20Kingdom/))
- http://data.hisparc.nl/analysis-session/kehs292/data/
([vagrant](http://127.0.0.1:8081/analysis-session/kehs292/data/))

### CODE REVIEW

**Comment by 153957** [comment]
Old code used to determine of marker tooltips (station numbers) should be shown on the map, and what the size of the markers should be depending on the zoom level:

Labels:
```javascript
getLabel: function(feature) {
    if (map.getZoom() >= 14) {
        return feature.attributes["id"];}
    else {
        return ''}},
```
Marker size
```javascript
getSize: function(feature) {
    return .55 * map.getZoom();}};
```

**Comment by 153957** [comment]
New:
- the popup shows when clicking a marker
- the tooltip shows on hover
- marker size stil need to be made dynamic (see above)

screen shot 2016-10-11 at 23 42 15

Old:

screen shot 2016-10-11 at 23 41 46

**Comment by tomkooij** [comment]
Looks nice!

**Comment by 153957** [comment]
Concerning retina screens:
Leaflet has a detectRetina option (default: false), but it simply requests tiles from a more zoomed-in layer. However, CARTO also provides @2x tiles, which may be preferable when zoomed in to the highest zoom level, which occurs for single station maps. But then the tile server url should be set dynamically, which should be easy since Leaflet can inform you if the screen is retina: http://leafletjs.com/reference.html#browser-retina .

**Comment by 153957** [comment]
Added link to first post with links to all pages containing a map (including links to the same page in a local publicdb Vagrant machine, requires a fairly complete database)

**Comment by 153957** [comment]
Almost ready..

**Pull request merged**
