### PR TITLE
Django 1.7 Compatibility

### PR DESCRIPTION
**Pull request by 153957**
(original issue: #53)

Things to lookout for when upgrading to Django 1.7:

- [x] Requries Python 2.7, should not be an issue.
- [x] Schema migrations now handled by Django, so remove South and [migrate the migrations to Django](https://docs.djangoproject.com/en/dev/topics/migrations/#upgrading-from-south).
    - [x] Ensure all installs are fully up-to-date with their migrations.
    - [x] Remove south migrations
    - [x] Run (on vagrant) `python manage.py makemigrations`
    - [x] ~~Run (on server) `python manage.py migrate`~~ provision does this
    - [x] Deal with south add_introspection_rules for SerializedDataField
        - [x] Tested, no problems so far..
- [x] ~~New method on custom Field subclasses~~
- [x] Form validation changes (no need to return cleaned_data, etc)
    - [x] Tested
- [x] Replace deprecated `mimetype` with `content_type`
- [x] New WSGI application handler
- [x] django.setup() required in `hisparc-update` script
- [x] Initial data loading has changed, especially when migrating
    - [x] Initial data for generator state
    - [x] Initial data for histogram types
- [x] Add core plot to analysis session results.. just because..

To update server:

- [ ] Remove `'south'` from `INSTALLED_APPS`
- [ ] After migrations, set the `last_run` datetimes back to their previous values

Check this page for more changes:
https://docs.djangoproject.com/en/1.7/releases/1.7/

### CODE REVIEW

**Comment by 153957** [comment]
Need to figure out how to deal with these lines in certain models:
```python
from south.modelsinspector import add_introspection_rules

class SerializedDataField(models.Field):
    add_introspection_rules([], ["^django_publicdb\.histograms\.models\.SerializedDataField"])
```

**Comment by 153957** [comment]
This should be all I think, I think we can merge this (first fixing the conflicts) and go about updating the server..

**Comment by davidfokkema** [comment]
Maybe first merge master into this branch, and then test an upgrade inside the vagrant VM?

**Comment by 153957** [comment]
Yes, that was my plan :)

**Comment by davidfokkema** [comment]
👍

**Comment by 153957** [comment]
Server has been updated.

**Comment by davidfokkema** [comment]
Yes!

**Pull request merged**
