### PR TITLE
Management commands (and other improvements)

### PR DESCRIPTION
**Pull request by 153957**
Use Django management commands for frequently executed tasks instead of a separate script and an endpoint.

Benefits: Cleaner cron jobs, easier to test, use Django logging to guide log output, easier to build in options, no publicly available endpoint.

Todo:
- [x] Add easy install dev requirements make command (`make devinstall`)
- [x] Improve Model.Meta, add `verbose_name(_plural)`, use lists etc..
- [x] Disable XMLRPC Proxy calls during tests (if VPN_PROXY == None).
- [x] Build dictionaries for API using queryset methods instead of list comprehensions
- [x] Move manage.py up one directory for easier usage and less complicated config
- [ ] Rework analysissessions
    - [x] Use already found coincidences in ESD (CoincidenceQueries)
    - [ ] Lazily get traces from API to reduce required database storage (#38)
    - [ ] Double check trace alignment in frontend
    - [ ] Use number of particles + pulseheight for mips
    - [ ] Combine date and time database fields into datetime field (coincidences/events)
- [x] Rework/improve histogram jobs
    - [x] Add tests with real data files
    - [x] Test histogram models
    - [x] Test checks
    - [x] Test jobs
- [x] Rework status display views
    - [x] Make network summary a class based view
    - [x] Remove unnecessary source views, can be created with extra kwargs in urls
    - [x] Reduce SQL queries by using select_related/prefetch_related
    - [x] Replace `{% url name link.0 link.1 … %}` reverse lookups by `get_absolute_url`
- [x] Rework maps
    - [x] Use new data based status for map status indicators
    - [x] DRYer code, less queries
- [x] Test that the new commands work as expected
    - [x] createsessions
    - [x] updatehistograms
- [x] Remove unused pulseheight fits (monitoring)
- [x] Add caching (pip and conda) on Travis
- [ ] Improve data/coincidence download reliability
- [ ] Improve logging in case of notable errors/warnings
- [ ] Add cronic in case command still ends in error, see #188 - This can be more easily added once we upgrade to CentOS 7 (#230) when chronic is included in the `moreutils` package (available via yum/EPEL)

### CODE REVIEW

**Comment by 153957** [comment]
Another very focused pull request sticking exactly to the original goal :grimacing:

**Comment by davidfokkema** [comment]
Would it be best to merge this (once the checks pass) and split out several to-do chunks to other pull requests?

**Comment by 153957** [comment]
For more consistent tests this would benefit from https://github.com/HiSPARC/sapphire/pull/186

**Comment by tomkooij** [comment]
Wow! +1

**Comment by 153957** [comment]
I think this is about ready to be merged. I did not actually test 5ea7973 with an actual local VM, but it seems correct. Additional tests might be nice, for example for the jobs for coincidences/reconstructions/station offsets.. but that can be done later.

@tomkooij Could you review this today? (and merge & deploy if you wish).

**Comment by 153957** [comment]
The tests with actual data are mostly important for a transition to Python 3, to ensure that that all keeps working as expected..

**Comment by davidfokkema** [comment]
There are problems with 5ea79736d5601e2ea368d01da7e09fe252ac6d3d. The ``publicdb_base`` variable is also used in roles/publicdb/defaults/main.yml for the filesystem location of publicdb. So I got this building the VM:
```
TASK [publicdb : install packages in conda environment using pip] **************
fatal: [publicdb]: FAILED! => {
    "changed": false,
    "cmd": "http://localhost:80/publicdb/publicdb_venv/bin/pip list --format=freeze",
    "rc": 2
}

MSG:

[Errno 2] No such file or directory
```
because of these lines in provisioning/roles/publicdb/defaults/main.yml
```
publicdb_base: /srv/
publicdb_path: "{{ publicdb_base }}publicdb/"

publicdb_code: "{{ publicdb_path }}www/"
publicdb_venv: "{{ publicdb_path }}publicdb_venv"
```
Both uses of ``publicdb_base`` mean entirely different things, unfortunately.

**Comment by 153957** [comment]
Good catch, thanks!
I will rename it to `publicdb_host` or `publicdb_base_url`

**Comment by kaspervd** [comment]
Thanks @153957!

**Pull request merged**
