### PR TITLE
Updates for Django 1.9

### PR DESCRIPTION
**Pull request by 153957**
Todo:

- [ ] ~Fix git clone in local VM. It does take the local repo, but does not checkout its local HEAD.~ #178
- [x] Check if migrations work correctly.
- [ ] Fix data page `TemplateSyntaxError` `Invalid filter: '…'` (where … is some custom filtertag)

### CODE REVIEW

**Comment by tomkooij** [comment]
Why upgrade to 1.9? It is not an LTS and support has all but ended. Will end this month. 

(Are you working towards 1.11 LTS? )

**Comment by 153957** [comment]
Yes, going towards 1.11 LTS, which should be released approximately tomorrow :)

**Comment by 153957** [comment]
To test this I had to add `version: django19` to the `checkout publicdb in /srv/publicdb/www` task to ensure this repo was properly checked out in the VM. See #178.

**Comment by tomkooij** [comment]
I loaded a database dump into my VM with this branch and that has some issues (errors on import, no summaries in the database). 

I used `170329_publicdb_dump.sqlc` because that was on my laptop. That just might be too old, but beware!

**Comment by tomkooij** [comment]
Mmmh... I loaded a recent database dump into a VM provisioned with `master` and subsequently provisioned this branch.

I'm getting invalid filter exceptions in both coincidences and station station pages:
```
TemplateSyntaxError at /show/stations/6/2017/4/3/
Invalid filter: 'fix_timestamps_in_data'
```

**Comment by 153957** [comment]
Ill look into it

**Comment by 153957** [comment]
That templatetag is not the problem. If I remove that filter from the `singlesratelowdata` I get `Invalid filter: 'slice_data'` instead..

**Comment by tomkooij** [comment]
`templates/station_data.html` has many filters, but `templates/network_coincidences.html` fails as well. That might be a good starting point to figure out what is going on as it is a much smaller template.

**Comment by tomkooij** [comment]
I tracked down the problem:

`{% load fix_data %}` loads `fix_data` from the `publicdb.analysissessions` package. It seems unique names are needed, because django 1.9 changes the way it looks for / imports custom template filters.

**Comment by 153957** [comment]
Thanks!
In this case we can simply remove the templatetags from `analysissessions`. That app will then simply use the other (more complete) tag library from `status_display`, which also contains a (better) `fix_histogram_data`.

**Comment by tomkooij** [comment]
Was this merged intentionally? There is still the `TemplateSyntaxError`. `templatetags` from `publicdb.analysissessions` needs to be removed.

**Comment by 153957** [comment]
Yes, I did that fix in master eb81af4e5fad91ab084ec5182d94d666002045db.
I had already merged this branch into master locally so I did this fix in my local master as well, tested it in the VM and then deployed it to live.

**Pull request merged**
