### PR TITLE
Add support for singles

### PR DESCRIPTION
**Pull request by tomkooij**
This adds singles into the ESD. Tested in my VM. 

Singlerates (both above low and high thresholds) are added as `DailyDataset` tables (150 sec **averages**, I know averaging has its problems, but since rates are not continuous, this is IMO better than sampling. Weather (continous) data is sampled at about 150s intervals).

Singlerate histrograms are saved as `DailyHistogram` tables.

ToDo:
- [x] Add singles to summaries (`needs_update_singles`, `num_singles`).
- [x] Import singles data into ESD
- [x] Create daily histograms
- [x] Add thresholds to status display (now relevant)
- [x] Add singles to download form
- [x] PEP8

### CODE REVIEW

**Comment by tomkooij** [comment]
Example of histograms on daily status page:

image

**Comment by 153957** [comment]
Perhaps make the singles vs time plots less high (like the eventtime / barometer / temperature plots). Otherwise the page will get very long..

**Comment by tomkooij** [comment]
I tried, but the difference between channels as seen in the top most plot was much less clear.
I'll fiddle with it some more.

**Comment by 153957** [comment]
Ok. No worries, it is probably fine for now.

**Pull request merged**
