### PR TITLE
Use Arrayfields for data/histogram models

### PR DESCRIPTION
**Pull request by 153957**
Initial step for #175. This was the easiest first step because the networkhistograms are all one dimensional.

The bins and values are arrays of PositiveIntegerFields.
This allows 32-bit integers, but with min value of 0 (i.e. 0-2147483647).
Remove save overwrite, Django now handles this properly.
No changes required in the views.

The Postgres table size (for my local database) increased from 3MB to 5.9 MB (later increased further, see next comment).
I did perform `VACUUM FULL histograms_networkhistogram` to remove the temporary space required during the migration.
Postgres does not compress (TOAST) the table since the individual array sizes are relatively small.

**Warning!! No backwards migration!**
I tried to create a simple one, basically the inverse of the forwards,
but it caused some issues where the fields were not properly stored.
For testing purposes it might be nice to get this working.

~~(*Note*: currently branched of the classbased-views branch: #205 )~~

@davidfokkema @tomkooij @kaspervd 

Todos:
- [x] Deprecate SerializedDataField class (fix references in old migrations).
- [x] Convert SerializedDataFields in coincidences app to ArrayFields.
- [x] Prepare ForeignKeys for newer Django; explicit on_delete (CASCADE).
- [x] Use ADC instead of mV for puleheights/integrals histograms (change in jobs). (#45)
- [x] Convert existing pulseheights/integrals from mV to ADC during data migration.
- [x] Update plot labels for mV
- [x] Update TSV texts
- [ ] Check other places which need updates;
    - [ ] Infopakket (https://github.com/HiSPARC/infopakket/pull/47)
    - [x] jsparc (https://github.com/HiSPARC/jsparc/pull/56)
    - [x] sapphire (https://github.com/HiSPARC/sapphire/pull/182)
- [x] Update factories
- [x] Update plots on help page

Nice to have:
- Add 'has_multiple_datasets' field to DatasetType model.

### CODE REVIEW

**Comment by 153957** [comment]
The migrations have a progressbar to allow you to keep track of progress.
For me they took approximately 2 hours.

Locally I am using a database from July 2017.
Here are approximate sizes after the migrations (I am uncertain how reliable the sizes reported in Postico are).

| Model | Before | After |
|---|---:|---:|
| DailyDataset | 37MB | 90MB |
| MultiDailyDataset | - | 2MB |
| DailyHistogram | 706MB | 86MB |
| MultiDailyHistogram | - | 683MB |
| NetworkHistogram | 3MB | 17MB |

**Comment by 153957** [comment]
Possible todos:
- Convert SerializedDataFields in coincidences app to ArrayFields.
- Remove SerializedDataField class.
- …

**Comment by davidfokkema** [comment]
I probably forgot. What's the upside of using ArrayField? Is it just the replacing of a custom field with a properly supported one? Or are there other benefits? It's not disk space, for sure.

**Comment by 153957** [comment]
True, but disk space usage does not seem that bad, only ~20% more.

- ArrayFields can be queried directly.
- Easily Sum values in SQL.
- Can view data in database viewer (Positco).
- Automatic validation by Django, no longer need the `ast.literal_eval`.
- More clearly defined data shape and format (can be a bit more constrained).
- Possibly faster because no need to unzip/unpickle.
- Prevent possible pickle issues when transitioning to Python 3.

**Comment by 153957** [comment]
Sorry for all the changes unrelated to the main goal of this PR… ☺️

**Comment by 153957** [comment]
Converting the events to arrayfields takes very long, progressbar indicates about 6 hours for my local database. Converting the traces from mV to ADC should also help reduce the required size of the data as arrayfields. Additionally, removing events from old/expired sessions can help.

**Comment by 153957** [comment]
I used the following code to remove events from sessions which ended at least a week ago.
This reduced the number of events from 276634 to 41471.
And the size of the database from 208 MB to 35 MB.
This should significantly reduce the time the migration will cost.

```python
import datetime
from sapphire.utils import pbar

some_time_ago = datetime.datetime.now() - datetime.timedelta(days=7)
oldsessions = AnalysisSession.objects.filter(ends__lt=some_time_ago)

for session in pbar(oldsessions):
    analyzecoincidences = session.analyzedcoincidence_set.all()
    for analyzecoincidence in analyzecoincidences:
        events = analyzecoincidence.coincidence.events.all()
        events.delete()
```

**Comment by tomkooij** [comment]
Nice work!

**Pull request merged**
