### PR TITLE
Reorganise provisioning scripts.

### PR DESCRIPTION
**Pull request by 153957**
Group tasks/handlers/files/templates into roles.
Update reboot handler to use wait_for_connection (Ansible 2.3).
Create host groups.

Todo:
- [x] Move some paths like virtual env into group_vars
- [x] Move reused paths/variables/versions into group_ or host_vars
- [x] ~~Fix uWSGI install error~~ Recreated the base image and ran provisioning without issue.
- [x] Test if it correctly shows an error after rebooting a local VM during provisioning to indicate that `/vagrant/` needs to be remounted:
```
$ vagrant up datastore

…

RUNNING HANDLER [common : reboot] **********************************************
changed: [datastore]

RUNNING HANDLER [common : wait for server to come back] ************************
ok: [datastore]

RUNNING HANDLER [common : fail if dev] *****************************************
fatal: [datastore]: FAILED! => {
    "changed": false
}

MSG:

Reboot VM with vagrant to remount shared folders and continue provisioning, using `$ vagrant reload --provision`


$ vagrant reload --provision datastore

...

PLAY RECAP *********************************************************************
datastore                  : ok=51   changed=38   unreachable=0    failed=0   

```
- [ ] Test local provisioning:
    - [x] publicdb
    - [ ] vpn - see #168
    - [x] datastore
- [ ] Reenable provisioning common tasks for base image
- [ ] allow provisioning of VMs without vault password

### CODE REVIEW

**Comment by 153957** [comment]
Hmm, my current uWSGI installation problems are possibly related issues raised in this thread by @davidfokkema :
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/JVxrCz9TZlI

**Comment by 153957** [comment]
@davidfokkema @tomkooij @kaspervd 
I think this is ready, this PR does not fix #168.. so the VPN VM does not properly provision.
I could look into reenabling preprovisioning of the base image with common tasks..

**Comment by davidfokkema** [comment]
Wonderful! Hopefully, I can find some time in the next few days to study this. This was a *lot* of work, thank you for taking the time!

**Comment by tomkooij** [comment]
Wow. Just wow! I'm going to try to review this next week!

**Comment by tomkooij** [comment]
provisioning a `publicdb` dev VM works fine on Linux, although I had to upgrade Vagrant because of the `ansible.compatibilty_mode` in `Vagrantfile`.

Windows/ansible_local is giving me headaches. I'll look into it later.

**Comment by 153957** [comment]
Roles still contain tasks, so tasks are still a thing, and you can still define separate task files and include those (which can sometimes be useful to push a specific change to all servers).

But by having roles you can also more easily keep files/templates related to tasks in the same role. Having specific variables for roles. It is clearer which tasks are related, and which depend on others.

True about the 'lot of files' I am also not a big fan of all the `main.yml`, which can get annoying in a code editor to know which is which, you have to look at the full path.. but it is the recommended way: http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout

**Pull request merged**
