### PR TITLE
Run with Python 3

### PR DESCRIPTION
**Pull request by 153957**
Thus far I only ran `2to3` and fixed some of the code touched.

Todo:

- [x] Run 2to3
- [x] Change used Python version in provisioning to 3.6
- [x] Change used Python version on Travis to 3.6
- [ ] Fix unicode <-> bytes issues.
- [ ] Test everything (event processing, etc..)
- [ ] Some other improvements
- [ ] …

Implements #155

Deadline: 2020 ( https://pythonclock.org )

### CODE REVIEW

**Comment by 153957** [comment]
I did some initial work to convert the publicdb to Python 3. I currently do not have the time to finish this. If someone else could help finish this, that would be nice.

I think the biggest task will be checking unicode strings vs byte strings.
Some more tests might be useful to cover more models and views.

**Comment by tomkooij** [comment]
I'll have a look (but low priority)

**Comment by 153957** [comment]
Probably to many conflicts now. Might be better to do this properly at some other point on the (then-)current master

**Comment by tomkooij** [comment]
I agree. Closing!

**Pull request closed without merging**
