### PR TITLE
Updates

### LINKED ISSUE #155: Transition to Python 3
Python 2 will be end-of-life in a few years.
The publicdb should be transitioned to Python 3.
SAPPHiRE is already Python 3 compatible.
publicdb does not need to keep backwards compatible with Python 2.

See discussion at: https://github.com/HiSPARC/sapphire/pull/154#issuecomment-257255562

### PR DESCRIPTION
**Pull request by 153957**
Summary of most important changes:
- Remove Nagios
    - We recently discussed that this is probably not useful to keep around. We already determine status based on data availability, although this may be slower in noticing a problem, and does not (yet) detect all the same issues, it is easier to maintain.
- Update to Python ~3.8+~ 3.10
    - 3.7 was an option, but 3.8 had longer support and a few nice features which I used while updating.
    - Fixes #155
- Upgrade to Django 3.2
    - Current LTS
- Upgrade to Postgres 14
- Fix generating new IPs for Pcs
    - Just use the standard library ipaddress package for easier IP handling
- Fix bytes -> string encoding
    - Mostly relevant for tests where we retrieve/get a response and compare it to an expected value
- Fix tests
- Increase max_length for many CharFields on models
    - Many of the values generated by Faker during tests were longer than the allowed lengths, increasing the max_length fixes this.
- Replace raven by sentry-sdk
- Replace Travis CI by GitHub Actions
- Update Docker-compose
- Remove Vagrant and packer configurations

Going through this commit by commit might be clearest in order to understand the changes.

### CODE REVIEW

**Comment by 153957** [comment]
Getting all tests to pass always may depend on this being merged first: https://github.com/HiSPARC/sapphire/pull/194

Note in this PR it seems like the 3.10 tests succeeded, while the same tests for the same commit failed here: https://github.com/153957/publicdb/runs/7297479458?check_suite_focus=true

**Comment by davidfokkema** [comment]
This is a very large PR and it will take me some time to digest it. Few questions:

1. For what exactly do we use Docker?
2. What happens when station pc's no longer can reach nagios? Or do we keep that running on tietar? In that case, should we copy that over to Utah?
3. For what do we use Sentry? Is there a status page or something like that?

Thanks for your work!

**Comment by 153957** [comment]
> 1. For what exactly do we use Docker?

I used it for local testing. Maybe I should add some instructions to the readme :)
Something like this:
- Install Docker Desktop 
- Run `docker-compose up -d` in the repository directory
- In your browser go to http://localhost:8000 to interact with the publicdb.

And then some additional steps to actually get it running, by creating a superuser, and creating the generator state model. Or maybe loading the live database or a fixture..

However, in the mean time you can do thing like this to run the tests:
`docker-compose exec publicdb make unittests`

> 2. What happens when station pc's no longer can reach nagios? Or do we keep that running on tietar? In that case, should we copy that over to Utah?

Nagios is indeed on tietar, it is separate from the publicdb. However, it receives part of its configuration from the publicdb. The VPN is also on tietar and also gets its config (instructions to make new keys) from the publicdb. I suggest also stopping Nagios on tietar, and not moving that to Utah. We probably do want to keep the VPN.

About not reaching Nagios; I would have to check the station-software code, but I think it will just keep trying and failing. There are several parts which talk to Nagios, some checks were Nagios asks the station to check something, those will simply not happen anymore. Checks where the station tries to report to Nagios will fail, Im not certain if we have graceful retries, or just ignoring failures, and hoping the next will succeed..

> 3. For what do we use Sentry? Is there a status page or something like that?

We have an account with the Beheer HiSPARC email account on sentry.io to help investigate server errors (uncaught exceptions) happening in the publicdb.
We see some errors happening regularly, mostly IOErrors, which may be caused by interrupted data downloads.
Screenshot 2022-07-12 at 21 15 43
The only change here is that we can use a newer package to report these errors to Sentry. raven was the old integration but is no longer supported/updated.

**Comment by tomkooij** [comment]
> > 2. What happens when station pc's no longer can reach nagios? Or do we keep that running on tietar? In that case, should we copy that over to Utah?

> About not reaching Nagios; I would have to check the station-software code, but I think it will just keep trying and failing. There are several parts which talk to Nagios, some checks were Nagios asks the station to check something, those will simply not happen anymore. Checks where the station tries to report to Nagios will fail, Im not certain if we have graceful retries, or just ignoring failures, and hoping the next will succeed..

Many school have been blocking the VPN connections for years. So "unable to contact Nagios" has been field tested extensively. It works fine ;-)

I have not had a chance to review this.

**Comment by davidfokkema** [comment]
> Many school have been blocking the VPN connections for years. So "unable to contact Nagios" has been field tested extensively. It works fine ;-) The docs probably need updating if we throw out Nagios altogether.

So... how useful is the VPN then, currently? This would also be a problem for any super-highly-advanced-new-data-acquisition system. If you can't reach the computers, you can't update anything.

**Comment by 153957** [comment]
Without Nagios the VPN would just be used to remotely connect (VNC) to the stations. Software updates on machines running the station-software happen via the publicdb updates (data.hisparc.nl/software-updates/), no VPN needed. For PySPARC(-like) machines it would be useful/required to have remote access via VPN (or ensure they have a public IP or at least some public address) for management/updates.

**Comment by davidfokkema** [comment]
Indeed!

**Comment by 153957** [comment]
Note; Upgraded database to postgres 14.

Can either use [`pg_upgrade`](https://www.postgresql.org/docs/current/pgupgrade.html) or make a database dump, upgrade postgres, then load the dump.

I think the dump will be easier, otherwise it requires keeping the old postgres binary available. Will need to verify that database constraints are probably set and correct access/roles are assigned.

**Review by davidfokkema — APPROVED** [review]

**Pull request merged**
