### PR TITLE
Include 'tietar' in provisioning setup

### PR DESCRIPTION
**Pull request by davidfokkema**
Tietar, the VPN / monitoring server, is limping along. Let’s provision this server, just like we do with Pique. Including tietar in this repository allows us to reuse some VM / provisioning stuff, *and* allows us to build out the staging environment so we can test interactions between data.hisparc.nl and vpn.hisparc.nl.

~~Maybe we should break out all tietar stuff, but hey, doing things perfectly is a luxury.~~

Tasks:
- [x] openVPN
- [x] dnsmasq
- [x] nagios refresh script
- [x] key management script
- [x] nagios
- [x] firewall
- [x] check reload nagios config after editing on publicdb
- [x] fix generating keys when a new pc is added
- [x] check downloading keys
- [x] notification emails

### CODE REVIEW

**Comment by 153957** [comment]
It seems like a good idea to include it in this repository, since the two servers are so closely linked.

**Comment by davidfokkema** [comment]
Good, we'll keep it in this repository.

**Comment by davidfokkema** [comment]
I think it's actually done, bugs notwithstanding.

**Comment by 153957** [comment]
Ok cool!

**Comment by davidfokkema** [comment]
Now waiting for the hardware to be installed.

**Comment by 153957** [comment]
Will happen either today or Monday.

**Comment by 153957** [comment]
Reloading config works, but still some difficulties in adding MPV checks on pique (`monitorpulseheightthresholds`)

**Comment by davidfokkema** [comment]
Ready!

**Pull request merged**
