### PR TITLE
Fix reading from file while it is also being written to

### LINKED ISSUE #123: Some concurrency issues in event jobs
When updating event histograms for Summaries using multiprocessing there appears to be the possibility of strangeness.. The file exists, there should be only one writer. Perhaps the readers had issues with another process writing? Curious because I would expect PyTables to leave existing data alone when writing new (reconstruction) tables.

This was previously not an issues because data for the ESD was read from raw data, save in tmp location and written to ESD by 1 writer.
Now many readers read from ESD, save to tmp location and reconstructions are written to ESD by 1 writer.
So reading and writing to/from the same source.

Perhaps make the job smarter to wait until all jobs for a specific date are done before writing the results.

```
INFO - [27616] - Updating event histograms for Summary: 3201 - 27 Oct 2015
INFO - [27618] - Updating event histograms for Summary: 1009 - 27 Oct 2015
INFO - [27615] - Updating event histograms for Summary: 511 - 27 Oct 2015
INFO - [27617] - Updating event histograms for Summary: 510 - 27 Oct 2015
INFO - [27616] - Updating event histograms for Summary: 509 - 27 Oct 2015
INFO - [27618] - Updating event histograms for Summary: 508 - 27 Oct 2015
INFO - [27616] - Updating event histograms for Summary: 507 - 27 Oct 2015
ERROR - [27581] - Exception occured.
Traceback (most recent call last):
  File "scripts/hisparc-update.py", line 44, in <module>
    run()
  File "scripts/hisparc-update.py", line 27, in run
    completed = hg.jobs.update_all_histograms()
  File "scripts/../django_publicdb/histograms/jobs.py", line 176, in update_all_histograms
    perform_update_tasks()
  File "scripts/../django_publicdb/histograms/jobs.py", line 188, in perform_update_tasks
    update_histograms()
  File "scripts/../django_publicdb/histograms/jobs.py", line 286, in update_histograms
    perform_events_tasks)
  File "scripts/../django_publicdb/histograms/jobs.py", line 312, in perform_tasks_manager
    for summary, tmp_location in results:
  File "/srv/publicdb/publicdb_env/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 604, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1085, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 294, in H5F_super_read
    unable to load superblock
  File "H5AC.c", line 1320, in H5AC_protect
    H5C_protect() failed.
  File "H5C.c", line 3574, in H5C_protect
    can't load entry
  File "H5C.c", line 7954, in H5C_load_entry
    unable to load entry
  File "H5Fsuper_cache.c", line 476, in H5F_sblock_load
    truncated file: eof = 393973760, sblock->base_addr = 0, stored_eoa = 393985274

End of HDF5 error back trace

Unable to open/create file '/srv/publicdb/www/esd/2015/10/2015_10_27.h5'
```

### PR DESCRIPTION
**Pull request by 153957**
Get results from tasks in correct order (by date).
Wait until all jobs for a specific date are done before storing the
data.
Some refactoring work.
First do coincidence histograms, should be very quick.
Perhaps this will be reversed later when station offsets will also be
determined.

Should fix #123

Todo:
- [x] Test it

### CODE REVIEW

**Comment by davidfokkema** [comment]
You're doing some great work!

**Comment by 153957** [comment]
Just stuff that needs fixing.. some other important thingy needs some attention too.. :wink:

**Comment by tomkooij** [comment]
Very nice! :clap:

**Comment by davidfokkema** [comment]
@153957 now what would that be? 😉

**Pull request merged**
