### PR TITLE
Django 1.10

### PR DESCRIPTION
**Pull request by 153957**
See: https://docs.djangoproject.com/en/1.10/releases/1.10/

Todo:
- [x] Install Django 1.10
- [x] Middleware
- [x] Install Django 1.10 on Travis
- [x] Fix reverse urls, use view names.
   `"The ability to reverse() URLs using a dotted Python path is removed."`
   See https://github.com/django/django/pull/7417/files for new relevant documentation for reusing the same view name.
   Also see https://docs.djangoproject.com/en/1.10/topics/http/urls/#url-namespaces-and-included-urlconfs for settings namespaces per app to prevent url name collisions.
    - [x] Fix `redirect()` using url names..

### CODE REVIEW

**Comment by tomkooij** [comment]
Nice! don't forget to review and merge #183 before provisioning this on pique.

**Comment by 153957** [comment]
Not many 'dangerous' changes in this, mostly reworking the url configurations, redirects etc..
But it might be nice if someone reviewed it a bit.

**Comment by tomkooij** [comment]
Will do!

**Comment by 153957** [comment]
Deployed!

**Comment by tomkooij** [comment]
Nice work!

**Pull request merged**
