### PR TITLE
Automatic station reconstructions

### PR DESCRIPTION
**Pull request by 153957**
This should add automatic event reconstruction to the ESD.
Only for 4-detector stations with an available station layout.

Still some tasks left to do:
- [ ] Test it in a VM
    - [x] Jobs
        - [x] Station with layout
        - [x] Station without layout
    - [x] Station data page histograms
    - [x] Source TSV
    - [x] Automatic flags on updated layout
- [x] Add downloading of reconstructions, ~~either~~ along event download, ~~or separate~~
    - [x] If combined output -999 when no reconstructions are available
    - [ ] Add event reconstructions to events in coincidence downloads
- [x] Automatic summary flagging when new layout is available (when a layout is saved, only for 4 detector stations)
- [x] Filter to only do for 4-detector stations
- [x] Require newer version of SAPPHiRE
- [ ] ~~Perhaps disable core reconstruction~~
- [x] Disable progressbar for reconsutruction
- [x] Update docs (data_access)
- [x] Flip order of azimuth/zenith to zenith/azimuth

Units:
- [x] degrees
- [ ] ~~radians~~

Note:
- [x] When deploying manually add the new histogram types on server.

### CODE REVIEW

**Comment by tomkooij** [comment]
Nice work!

**Comment by 153957** [comment]
Some questions:

- Should the reconstructions (azimuth/zenith) be downloadable via the esd events download or as a separate file? (in case of combined file SAPPHiRE could separate them again when downloaded)
- Currently angles are given in degrees, while radians are used in the ESD. Degrees can be rounded more easily than radians, and are easier to understand for most.
- Currently the azimuth angles go from -180° to 180°. Should that be changed to 0° to 360° to keep -1 and -999 available as error codes? (-1 is not very applicable, perhaps to indicate no reconstructions were attempted, and -999 for failed reconstructions)

(@davidfokkema @tomkooij @SBeijen @NiekSchultheiss @renaldo20)

**Comment by tomkooij** [comment]
Download reconstructions along with events.

I'm happy with angles in radians and NaN for missing or failed reconstructions. -999 is an alternative for nan usable with degrees and radians.

I don't mind switching to degrees, but do not understand the rounding. Why is rounding easier for degrees?

**Comment by 153957** [comment]
Because angles in integer degrees are accurate enough for the reconstructions allowing values to be integers. 1° in radians is 0.0175, requiring more numbers. How familiar are high-school students with radians?

**Comment by 153957** [comment]
I'd prefer not to use NaNs in TSV files, I'd rather use -999.

**Comment by tomkooij** [comment]
Degrees are certainly easier for high-school students. They should be able to calculate with radians, but most cannot "picture" angles in radians without converting to degrees first.

**Comment by 153957** [comment]
Everything seems to work, only the download part needs to be figured out.

**Comment by 153957** [comment]
Current look:

histograms

**Comment by tomkooij** [comment]
:clap:

**Comment by 153957** [comment]
Downloading for single station added.

Does not improve download speed :(

**Comment by davidfokkema** [comment]
Wow, that looks good! How badly does it affect download speed?

**Comment by 153957** [comment]
From local VM

Without reconstructions (i.e. current): ~450 KB/s
With reconstructions and reconstructed: ~100 KB/s
With reconstructions and not reconstructed: ~480 KB/s

**Comment by tomkooij** [comment]
:clap: again!

Regarding speed, I would suspect:
https://github.com/HiSPARC/publicdb/blob/5ea690ac754adef982a09415a5e780a37fff88df/django_publicdb/raw_data/views.py#L323

We need to figure out how to speed up the ```__getitem__``` query in:
 ``` yield event, reconstructions[event['event_id']]```

**Comment by 153957** [comment]
Possibly by pre caching the azimuth/zenith columns?
Something like:
in reconstruction try/except
```python
azimuths = reconstructions.col('azimuth')
zeniths = reconstructions.col('zenith')
```
in loop
``` python
id = event['event_id']
yield event, {'azimuth': azimuths[id], 'zenith': zeniths[id]}
```


Note; Im also not very happy with the current download speed (without reconstructions).

**Comment by 153957** [comment]
:shipit:

**Pull request merged**
