### PR TITLE
Use PostgreSQL instead of MySQL

### PR DESCRIPTION
**Pull request by 153957**
These changes mean that MySQL is no longer installed (not explicitly uninstalled).
And PostgreSQL (9.6) will be installed.

The MySQL version is to old for more recent versions of Django.
PostgreSQL is a nicer database to work with, it also supports [Array fields](https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#arrayfield) which means the SerializedDataFields are no longer required.

On my local VM it seems to work fine. Using `dumpdata` and `loaddata` I was able to load all tables except the histograms and coincidences (and analysissessions). The first two of those tables are very large (multiple GB) when written to JSON, which causes MemoryErrors when loading them in the VM (even though I gave it more RAM). A simple SQL dump from MySQL wont work, because PostgreSQL can not ingest that. I will have to figure out how to nicely migrate all histograms. Perhaps the dumped JSONs can be chopped into smaller chunks..

Todo:
- [x] Figure out how to migrate the histograms/coincidences(/analysissessions).
- [x] Use `py-myqsl2pgsql` to migrate the data.
- [ ] Perhaps a temporary task to remove MySQL, or do that manually.
- [x] Some cleanup, the .pgpass and database passwords may be unnecessary with the current permissions.
- [x] Test if the postgresql backup dumps work as expected.

### CODE REVIEW

**Comment by 153957** [comment]
My current plan:

- Dump the data, separate the histograms, coincidences and analysissessions:
``` bash
./manage.py dumpdata --indent 1 --natural-foreign contenttypes > ~/dump_contenttypes.json
./manage.py dumpdata --indent 1 --natural-foreign histograms > ~/dump_histograms.json
./manage.py dumpdata --indent 1 --natural-foreign coincidences > ~/dump_coincidences.json
./manage.py dumpdata --indent 1 --natural-foreign --exclude contenttypes --exclude coincidences --exclude histograms > ~/dump_nodata.json
```
- Split the large JSON files into smaller chunks. Each dumped JSON is a simple array containing dictionaries for each database row. Splitting files on the comma's separating entries: `},\n{` and adding start `[` and end `]` brackets to the new files keeps the JSONs valid.
- Disable table triggers to prevent foreign key checks which would fail because some data does not exist yet:
```sql
ALTER TABLE coincidences_coincidence DISABLE TRIGGER ALL;
ALTER TABLE coincidences_coincidence_events DISABLE TRIGGER ALL;
ALTER TABLE ... DISABLE TRIGGER ALL;
```
- Load all data chunks individually
- Reenable table triggers:
```sql
ALTER TABLE coincidences_coincidence ENABLE TRIGGER ALL;
ALTER TABLE coincidences_coincidence_events ENABLE TRIGGER ALL;
```

**Comment by tomkooij** [comment]
Nice!

I suppose this will be a big step towards upgrading to the current Django LTS.

**Comment by tomkooij** [comment]
BTW, Instead of splitting the JSONs you might want to try the solving the out of memory error:

http://stackoverflow.com/questions/23047766/django-loaddata-out-of-memory/40508533#40508533

If that works, that is much cleaner and easier.

**Comment by 153957** [comment]
Thanks, I had not yet found that, I will try that. That should make it a lot easier, if I no longer need to disable all the triggers.

**Comment by davidfokkema** [comment]
Out of curiosity: you're using only PostgreSQL at Leukeleu?

**Comment by 153957** [comment]
Yes 😄

**Comment by tomkooij** [comment]
I just stumbled upon this: http://askbot.org/doc/mysql-to-postgres.html

I tried `py-myqsl2pgsql` in my local VM and it seems to "just work". Provisioning this branch did fail on Django migrate, but that might be just my VM.

My VM imported the nightly database backup and after stopping `mysqld` it still work, so I presume it is running PostgreSQL :)

**Comment by 153957** [comment]
Ah, that might be even easier. And hopefully faster, since loading the 4GB JSON takes quite a while..

**Comment by tomkooij** [comment]
It only took a few minutes on my slow i3 laptop.

**Comment by davidfokkema** [comment]
Wow, excellent!

**Comment by 153957** [comment]
Even with the `ijson` package and modifications the VM was not able to load the large JSON. So `py-mysql2pgsql` it is.

**Comment by 153957** [comment]
It indeed worked quite fast. All data seems to be accounted for, also the more tricky parts; the binary data and data blobs (histograms and datasets, and jSparc events) work fine.

I will clean up this PR a bit more, test the database dumps, and then:
- perform a MySQL dump on the live server
- load it locally
- migrate the data to PostgreSQL
- dump the PostgreSQL database
- copy that back to the live server
- provision the live server to install PostgreSQL
- then load the dump on the live server
- remove MySQL

I think I will do this Wednesday evening. So there will be a bit of downtime then.
(@kaspervd @tomkooij @davidfokkema)

**Comment by 153957** [comment]
The pg_dump by default creates larger files than the mysql dump. Compression methods can be turned on, which reduces the size a lot, but significantly increases the processing time. I believe we have space enough to do the plain dumps.

**Comment by davidfokkema** [comment]
@153957 can you test that process in a VM? Always a bit tricky...

**Comment by 153957** [comment]
I will, I basically tested the first 4 steps already.
I also provisioned my local machine with MySQL, and then added the PostgreSQL tasks.
So that should also work, but I can try it again.
And I will also test pg_restore in my VM from the created dump.

**Comment by 153957** [comment]
Seems to have worked fine. In the end I used the mysql to postgresql package to migrate the database instead of loading the dump.
I left the MySQL installation on the server for now, but stopped the MySQL service (also on boot).
The I also left the MySQL dump from before the migration in the dump backup.

**Comment by tomkooij** [comment]
Nice work!

**Comment by davidfokkema** [comment]
Very, very nice! Did you run the provisioner or should we test for accidental changes?

**Comment by 153957** [comment]
I ran the provisioner, multiples times actually, also do do some additional clean up of some old models.
So rerunning provisioning also works fine.

**Comment by tomkooij** [comment]
How do you import the dump into PostgreSQL? 

@153957 : Can you update README.md with instructions for privisioning a VM with a dump?

**Comment by 153957** [comment]
I will. Im not entirely certain on how the dump can best be imported.
Sometimes I get errors/warnings, and sometimes I dont, not entirely certain what the best settings are.
It is something along these lines:
`pg_restore --clean --if-exists --no-owner --no-acl --schema=public --dbname=publicdb publicdb_dump.sql`

I suggest simply placing the dump in your project folder so you can access is in the VM via `/vagrant/publicdb_dump.sql`

**Pull request merged**
