### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by 153957**
Goals: Get tests working again and add more test coverage

- [x] Use postgresql as test database
- [x] Apply isort
- [x] Run flake8-isort on Travis (requires all imported requirements to be installed, or listed)
- [x] Run test coverage
- [x] Get tests running
- [x] Get tests running on Travis
- [x] Ensure LF line endings
- [x] Fix model factories that can create too long texts, or use unexpected characters, for certain fields (or increase field sizes)
    - [x] Mostly a problem for 'country', max length from faker: 51.
    - [x] Also prevent unexpected characters for such fields, if they are used in urls, i.e. more slug like: `[a-zA-Z0-9_-]`. 
- [x] Improve tests
    - [x] Check if context contains expected
    - [x] ~~Enable template options debug=True for tests~~ does not work as expected, will not report errors for used variables missing from the context, only actual template errors.
    - [x] Add http/requests mock/settings overwrite to prevent checking nagios for status during tests.

### CODE REVIEW

**Comment by tomkooij** [comment]
I approved, based on the CI checks. I still cannot provision a VM on Windows. I have an new (larger, faster) SSD lying around that I need to swap into my laptop first.

I'm impressed with a the hard work you put into this. Code is looking cleaner and more readable. Nice work!

**Comment by davidfokkema** [comment]
How are you supposed to run the tests?

**Comment by 153957** [comment]
See `.travis.yml` for examples :)

You will need a local postgres server, I installed Postgres for Mac from:
https://eggerapps.at (May conflict with postgresql from homebrew, so choose one of them).
Then add `/Applications/Postgres.app/Contents/Versions/latest/bin` to your PATH, so you can simply do `createdb publicdb` in a terminal to create a new database, however, Django just creates and destroys a test database for tests automatically (using the postgres user).

**Comment by davidfokkema** [comment]
In the VM, it couldn't create a database so I took ``cp publicdb/settings_develop.py publicdb/settings.py`` from ``.travis.yml`` (as you suggested). The rest of your instructions for running in the VM were entirely accurate. I didn't install a postgres server on my Mac yet.

**Comment by davidfokkema** [comment]
Tests ran fine in my VM, I really like ``factory_boy`` and ``isort``!!! Nice work, Arne!

**Comment by 153957** [comment]
> In the VM, it couldn't create a database

Ah! the [`"psql_user"`]( https://github.com/HiSPARC/publicdb/blob/tests/provisioning/roles/publicdb/templates/settings.py#L23) in the VM is `hisparc`, and that user does not have the rights to create new databases.. which is required to run the tests.

**Pull request merged**
