### PR TITLE
Large TSV performance

### PR DESCRIPTION
**Pull request by 153957**
This way of generating the tsv is faster for large files/many rows.

### CODE REVIEW

**Comment by 153957** [comment]
Hmm, it is faster but the format is not yet good with the new method.

GET /show/source/detector_timing_offsets/501/ => generated 76271 bytes in 3334 msecs
GET /show/source/detector_timing_offsets/501/ => generated 120250 bytes in 191 msecs

The format for the evettime is fine, but for detector_timing_offsets it needs some modifications.

To fix:
- [ ] Outputs detector offsets as a tuple (single column), i.e. `(0, 3, 4.5, 3.25)`, should be in separate columns.
- [ ] None values are now printed as None instead of nan (we want nan).
- [ ] Duplicate subsequent values are not yet filtered.

**Comment by 153957** [comment]
Downloading all eventtime and detector_timing_offsets took 38 minutes and 2 minutes respectively before these changes. After this it took 5 minutes and 10 seconds respectively, i.e. ~10x speed up.

The results are almost equal, the new detector_timing_offsets do not show the second decimal if it is 0, so the values are still equal.

**Comment by tomkooij** [comment]
Nice work!

**Comment by davidfokkema** [comment]
Wow!

**Pull request merged**
